import { describe, expect, it, vi } from 'vitest';
import {
  buildUnitPathEnv,
  renderDashboardUnit,
  renderSystemdUnit,
  runServiceInstall,
  runServiceUninstall,
  type ServiceDeps,
} from './service.ts';

const UNIT_PATH = '/home/op/.config/systemd/user/orchestrator.service';
const DASHBOARD_UNIT_PATH = '/home/op/.config/systemd/user/orchestrator-dashboard.service';

const values = {
  version: '1.2.3',
  date: '2026-07-10',
  nodePath: '/opt/node/bin/node',
  entryPath: '/opt/lib/node_modules/@nvergez/orchestrator/dist/index.js',
  pathEnv: '/opt/node/bin:/usr/bin',
};

describe('renderSystemdUnit', () => {
  const unit = renderSystemdUnit(values);

  it('stamps the generated-by header, pointing hand-edits at drop-ins', () => {
    expect(unit).toMatch(/^# Generated by orc service install \(1\.2\.3, 2026-07-10\)/);
    expect(unit).toContain('orchestrator.service.d/');
  });

  it('pins ExecStart to the absolute node + entry resolved at install time', () => {
    expect(unit).toContain(
      'ExecStart=/opt/node/bin/node /opt/lib/node_modules/@nvergez/orchestrator/dist/index.js',
    );
  });

  it('carries the decided [Service] directives (issue #74)', () => {
    expect(unit).toContain('Type=simple');
    expect(unit).toContain('EnvironmentFile=%h/.config/orchestrator/env');
    expect(unit).toContain('Environment=PATH=/opt/node/bin:/usr/bin');
    expect(unit).toContain('Environment=NODE_OPTIONS=--enable-source-maps');
    expect(unit).toContain('SyslogIdentifier=orchestrator');
    expect(unit).toContain('Restart=always');
    expect(unit).toContain('RestartSec=5');
    expect(unit).toContain('WantedBy=default.target');
  });

  it('omits After=/Wants= ordering and WorkingDirectory, per the spec', () => {
    expect(unit).not.toMatch(/^After=/m);
    expect(unit).not.toMatch(/^Wants=/m);
    expect(unit).not.toMatch(/^WorkingDirectory=/m);
  });
});

describe('renderDashboardUnit (issue #87)', () => {
  const unit = renderDashboardUnit(values);

  it('starts the same entry point with the dashboard verb — one package, two units', () => {
    expect(unit).toContain(
      'ExecStart=/opt/node/bin/node /opt/lib/node_modules/@nvergez/orchestrator/dist/index.js dashboard',
    );
  });

  it('reads the same canonical env file and logs under its own identifier', () => {
    expect(unit).toContain('EnvironmentFile=%h/.config/orchestrator/env');
    expect(unit).toContain('SyslogIdentifier=orchestrator-dashboard');
    expect(unit).toContain('Restart=always');
  });

  it('points hand-edits at its own drop-in directory', () => {
    expect(unit).toMatch(/^# Generated by orc service install \(1\.2\.3, 2026-07-10\)/);
    expect(unit).toContain('orchestrator-dashboard.service.d/');
  });
});

describe('buildUnitPathEnv', () => {
  it('orders bin dirs first, then the standard tail', () => {
    expect(buildUnitPathEnv(['/opt/node/bin', '/home/op/.local/bin'])).toBe(
      '/opt/node/bin:/home/op/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    );
  });

  it('dedupes repeats, keeping the first occurrence', () => {
    expect(buildUnitPathEnv(['/usr/bin', '/opt/node/bin', '/usr/bin'])).toBe(
      '/usr/bin:/opt/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin',
    );
  });
});

interface DepsOverrides {
  which?: (name: string) => string | null;
  run?: ServiceDeps['run'];
  resolveEntry?: () => string;
}

const makeDeps = (overrides: DepsOverrides = {}) => {
  const out: string[] = [];
  const err: string[] = [];
  const systemCalls: string[][] = [];
  const written: { path: string; content: string }[] = [];
  const deps: ServiceDeps = {
    out: (line) => out.push(line),
    err: (line) => err.push(line),
    run:
      overrides.run ??
      ((command, args) => {
        systemCalls.push([command, ...args]);
        if (command === 'loginctl') return Promise.resolve({ stdout: 'Linger=yes\n' });
        return Promise.resolve({ stdout: '' });
      }),
    execPath: '/opt/node/bin/node',
    which:
      overrides.which ??
      ((name) => (name === 'orca' ? '/home/op/.local/bin/orca' : `/opt/tools/bin/${name}`)),
    resolveEntry:
      overrides.resolveEntry ?? (() => '/opt/lib/node_modules/@nvergez/orchestrator/dist/index.js'),
    writeUnit: (path, content) => written.push({ path, content }),
    removeUnit: vi.fn(() => true),
    unitPath: UNIT_PATH,
    dashboardUnitPath: DASHBOARD_UNIT_PATH,
    username: 'op',
    uid: 1000,
    version: '1.2.3',
    today: '2026-07-10',
  };
  return { deps, out, err, systemCalls, written };
};

describe('runServiceInstall', () => {
  it('writes both units, reloads, enables --now, and prints the paths + journalctl hints', async () => {
    const { deps, out, systemCalls, written } = makeDeps();

    await expect(runServiceInstall(deps)).resolves.toBe(0);

    // One ritual, two units (issue #87): daemon and dashboard install together.
    expect(written.map((unit) => unit.path)).toEqual([UNIT_PATH, DASHBOARD_UNIT_PATH]);
    expect(written[0]?.content).toContain(
      'ExecStart=/opt/node/bin/node /opt/lib/node_modules/@nvergez/orchestrator/dist/index.js',
    );
    expect(written[1]?.content).toContain(
      'ExecStart=/opt/node/bin/node /opt/lib/node_modules/@nvergez/orchestrator/dist/index.js dashboard',
    );
    // dir(node) + dir(orca) + dir(claude), deduped, then the standard tail.
    expect(written[0]?.content).toContain(
      'Environment=PATH=/opt/node/bin:/home/op/.local/bin:/opt/tools/bin:' +
        '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    );
    expect(systemCalls).toContainEqual(['systemctl', '--user', 'daemon-reload']);
    expect(systemCalls).toContainEqual([
      'systemctl',
      '--user',
      'enable',
      '--now',
      'orchestrator',
      'orchestrator-dashboard',
    ]);
    expect(out.join('\n')).toContain(UNIT_PATH);
    expect(out.join('\n')).toContain(DASHBOARD_UNIT_PATH);
    expect(out.join('\n')).toContain('journalctl --user -u orchestrator -f');
    expect(out.join('\n')).toContain('journalctl --user -u orchestrator-dashboard -f');
  });

  it('fails fast when the box has no systemd user manager at all', async () => {
    const { deps, err, written } = makeDeps({
      run: (command, args) =>
        command === 'systemctl' && args.includes('show-environment')
          ? Promise.reject(new Error('spawn systemctl ENOENT'))
          : Promise.resolve({ stdout: '' }),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('run `orc` under your own supervisor');
    expect(written).toHaveLength(0);
  });

  // Issue #91: same preflight, opposite fix. This box HAS systemd; the shell
  // (SSH/Orca, no XDG_RUNTIME_DIR) just cannot reach its user bus — so it must
  // get the doctor's one-liner, never "go find another supervisor".
  it('tells an unreachable user bus to export XDG_RUNTIME_DIR instead of blaming systemd', async () => {
    const { deps, err, written } = makeDeps({
      run: (command, args) =>
        command === 'systemctl' && args.includes('show-environment')
          ? Promise.reject(
              Object.assign(new Error('exit 1'), { stderr: 'Failed to connect to bus: No medium found\n' }),
            )
          : Promise.resolve({ stdout: '' }),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('export XDG_RUNTIME_DIR=/run/user/1000');
    expect(err.join('\n')).toContain('re-run `orc service install`');
    expect(err.join('\n')).not.toContain('your own supervisor');
    expect(written).toHaveLength(0);
  });

  it('fails when orca is not on PATH — the unit would be born broken', async () => {
    const { deps, err, written } = makeDeps({ which: () => null });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('`orca` not found on PATH');
    expect(written).toHaveLength(0);
  });

  it('only warns when claude is missing, and leaves its dir off the unit PATH', async () => {
    const { deps, err, written } = makeDeps({
      which: (name) => (name === 'orca' ? '/home/op/.local/bin/orca' : null),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(0);
    expect(err.join('\n')).toContain('`claude` not found on PATH');
    expect(written[0]?.content).toContain(
      'Environment=PATH=/opt/node/bin:/home/op/.local/bin:' +
        '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    );
  });

  it('fails with a build hint when dist/index.js is missing', async () => {
    const { deps, err, written } = makeDeps({
      resolveEntry: () => {
        throw Object.assign(new Error('ENOENT'), { code: 'ENOENT' });
      },
    });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('npm run build');
    expect(written).toHaveLength(0);
  });

  it('still exits 0 with linger off, but prints the exact sudo one-liner', async () => {
    const { deps, err } = makeDeps({
      run: (command) =>
        command === 'loginctl'
          ? Promise.resolve({ stdout: 'Linger=no\n' })
          : Promise.resolve({ stdout: '' }),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(0);
    expect(err.join('\n')).toContain('REQUIRED for reboot survival');
    expect(err.join('\n')).toContain('sudo loginctl enable-linger op');
  });

  it('never runs enable-linger itself — the warning is the whole reaction', async () => {
    const { deps, systemCalls } = makeDeps({
      run: (command, args) => {
        systemCalls.push([command, ...args]);
        return command === 'loginctl'
          ? Promise.resolve({ stdout: 'Linger=no\n' })
          : Promise.resolve({ stdout: '' });
      },
    });

    await runServiceInstall(deps);
    expect(systemCalls.some((call) => call.includes('enable-linger'))).toBe(false);
  });
});

describe('runServiceUninstall', () => {
  it('disables --now, removes both units, and reloads', async () => {
    const { deps, systemCalls } = makeDeps();

    await expect(runServiceUninstall(deps)).resolves.toBe(0);

    expect(systemCalls).toContainEqual([
      'systemctl',
      '--user',
      'disable',
      '--now',
      'orchestrator',
      'orchestrator-dashboard',
    ]);
    expect(deps.removeUnit).toHaveBeenCalledWith(UNIT_PATH);
    expect(deps.removeUnit).toHaveBeenCalledWith(DASHBOARD_UNIT_PATH);
    expect(systemCalls).toContainEqual(['systemctl', '--user', 'daemon-reload']);
  });

  it('keeps going when the unit was never installed', async () => {
    const { deps } = makeDeps({
      run: (command, args) =>
        args.includes('disable')
          ? Promise.reject(new Error('Unit orchestrator.service not loaded.'))
          : Promise.resolve({ stdout: '' }),
    });
    vi.mocked(deps.removeUnit).mockReturnValue(false);

    await expect(runServiceUninstall(deps)).resolves.toBe(0);
  });
});
