import { accessSync, constants, existsSync, mkdirSync, realpathSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { homedir, userInfo } from 'node:os';
import { delimiter, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileRunner, type CommandRunner } from '../kernel/orca.ts';
import { readPackageMeta } from './pkg.ts';

/**
 * `orc service install` / `orc service uninstall` (issue #74): a static
 * shipped unit cannot work — the npm-global bin path depends on how node
 * was installed, and systemd user units don't source shell profiles — so
 * the unit is GENERATED here, from this embedded template, with concrete
 * per-machine absolute paths. Re-running install is the refresh path after
 * a node/nvm upgrade; hand-edits belong in `orchestrator.service.d/`
 * drop-ins, which survive regeneration.
 */

/** Where the generated unit lands — a generated artifact, always overwritten. */
export function systemdUnitPath(): string {
  return join(homedir(), '.config', 'systemd', 'user', 'orchestrator.service');
}

/** The dashboard sidecar's unit — same directory, same generated-artifact rule. */
export function dashboardUnitPath(): string {
  return join(homedir(), '.config', 'systemd', 'user', 'orchestrator-dashboard.service');
}

export interface UnitTemplateValues {
  version: string;
  /** Install date, YYYY-MM-DD — the header stamps when it was generated. */
  date: string;
  nodePath: string;
  entryPath: string;
  pathEnv: string;
}

interface UnitIdentity {
  /** The unit name — the SyslogIdentifier and the drop-in directory stem. */
  name: string;
  description: string;
  /** CLI verb appended to the entry point; empty runs the daemon. */
  verb: string;
}

function renderUnit(identity: UnitIdentity, values: UnitTemplateValues): string {
  return `# Generated by orc service install (${values.version}, ${values.date}). Do not edit —
# re-run \`orc service install\` to regenerate; overrides go in
# ~/.config/systemd/user/${identity.name}.service.d/
[Unit]
Description=${identity.description}
Documentation=https://github.com/nvergez/orchestrator
# No After=/Wants=: network-online.target has no provider in the user
# manager, and ordering against the Orca system unit is forbidden —
# Restart=always + the tolerant boot healthcheck cover it.

[Service]
Type=simple
EnvironmentFile=%h/.config/orchestrator/env
Environment=PATH=${values.pathEnv}
Environment=NODE_OPTIONS=--enable-source-maps
SyslogIdentifier=${identity.name}
ExecStart=${values.nodePath} ${values.entryPath}${identity.verb === '' ? '' : ` ${identity.verb}`}
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
`;
}

/** The generated-unit spec, verbatim from issue #74's resolution. */
export function renderSystemdUnit(values: UnitTemplateValues): string {
  return renderUnit(
    {
      name: 'orchestrator',
      description: 'Slack-driven orchestrator-dispatcher daemon',
      verb: '',
    },
    values,
  );
}

/** The dashboard sidecar's unit (issue #87): same package, `dashboard` verb. */
export function renderDashboardUnit(values: UnitTemplateValues): string {
  return renderUnit(
    {
      name: 'orchestrator-dashboard',
      description: 'Orchestrator dashboard sidecar — read-only web view of live state',
      verb: 'dashboard',
    },
    values,
  );
}

const STANDARD_PATH_TAIL = ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'];

/** dir(node) + dir(orca) + dir(claude), deduped, then the standard tail. */
export function buildUnitPathEnv(binDirs: string[]): string {
  const seen = new Set<string>();
  const dirs: string[] = [];
  for (const dir of [...binDirs, ...STANDARD_PATH_TAIL]) {
    if (!seen.has(dir)) {
      seen.add(dir);
      dirs.push(dir);
    }
  }
  return dirs.join(':');
}

/** Minimal `which`: the first PATH entry holding an executable file. */
export function whichBinary(name: string, pathValue: string | undefined): string | null {
  for (const dir of (pathValue ?? '').split(delimiter)) {
    if (dir === '') continue;
    const candidate = join(dir, name);
    try {
      accessSync(candidate, constants.X_OK);
      if (statSync(candidate).isFile()) return candidate;
    } catch {
      // not here — keep scanning
    }
  }
  return null;
}

export interface ServiceDeps {
  out: (line: string) => void;
  err: (line: string) => void;
  run: CommandRunner;
  /** The running node binary — becomes the unit's ExecStart interpreter. */
  execPath: string;
  which: (name: string) => string | null;
  /** Realpath of the package's own dist/index.js — throws when unbuilt. */
  resolveEntry: () => string;
  writeUnit: (unitPath: string, content: string) => void;
  /** Returns whether the unit file existed. */
  removeUnit: (unitPath: string) => boolean;
  unitPath: string;
  dashboardUnitPath: string;
  username: string;
  version: string;
  today: string;
}

export function realServiceDeps(): ServiceDeps {
  return {
    out: (line) => process.stdout.write(`${line}\n`),
    err: (line) => process.stderr.write(`${line}\n`),
    run: execFileRunner,
    execPath: process.execPath,
    which: (name) => whichBinary(name, process.env.PATH),
    resolveEntry: () => realpathSync(fileURLToPath(new URL('../../dist/index.js', import.meta.url))),
    writeUnit: (unitPath, content) => {
      mkdirSync(dirname(unitPath), { recursive: true });
      writeFileSync(unitPath, content);
    },
    removeUnit: (unitPath) => {
      if (!existsSync(unitPath)) return false;
      rmSync(unitPath);
      return true;
    },
    unitPath: systemdUnitPath(),
    dashboardUnitPath: dashboardUnitPath(),
    username: userInfo().username,
    version: readPackageMeta().version,
    today: new Date().toISOString().slice(0, 10),
  };
}

export async function runServiceInstall(deps: ServiceDeps): Promise<number> {
  // Preflight (issue #74): no systemd user manager → fail fast, nothing else
  // on this box can host the unit; a missing orca CLI → a unit born broken.
  try {
    await deps.run('systemctl', ['--user', 'show-environment']);
  } catch {
    deps.err(
      '✖ systemd user manager unreachable — systemd user services are required; ' +
        'on other platforms run `orc` under your own supervisor',
    );
    return 1;
  }

  const orcaPath = deps.which('orca');
  if (orcaPath === null) {
    deps.err(
      '✖ `orca` not found on PATH — Orca is a hard prerequisite, a unit that cannot ' +
        'reach it is born broken. Install the Orca CLI, then re-run `orc service install`.',
    );
    return 1;
  }

  const claudePath = deps.which('claude');
  if (claudePath === null) {
    deps.err('⚠ `claude` not found on PATH — sessions cannot spawn until it is installed');
  }

  let entryPath: string;
  try {
    entryPath = deps.resolveEntry();
  } catch {
    deps.err(
      '✖ dist/index.js not found in this package — run `npm run build` first (dev ' +
        'checkout), or reinstall the package',
    );
    return 1;
  }

  const pathEnv = buildUnitPathEnv([
    dirname(deps.execPath),
    dirname(orcaPath),
    ...(claudePath === null ? [] : [dirname(claudePath)]),
  ]);
  const values = {
    version: deps.version,
    date: deps.today,
    nodePath: deps.execPath,
    entryPath,
    pathEnv,
  };
  // One ritual, two units (issue #87): there is never a "which parts did I
  // install?" state — the daemon and its dashboard sidecar ship together.
  deps.writeUnit(deps.unitPath, renderSystemdUnit(values));
  deps.writeUnit(deps.dashboardUnitPath, renderDashboardUnit(values));

  try {
    await deps.run('systemctl', ['--user', 'daemon-reload']);
    await deps.run('systemctl', ['--user', 'enable', '--now', 'orchestrator', 'orchestrator-dashboard']);
  } catch (error) {
    deps.err(`✖ systemctl failed after writing the units: ${String(error)}`);
    return 1;
  }

  deps.out(`✔ installed ${deps.unitPath} — enabled and started`);
  deps.out(`✔ installed ${deps.dashboardUnitPath} — enabled and started`);
  deps.out('  follow logs with: journalctl --user -u orchestrator -f');
  deps.out('  dashboard logs:   journalctl --user -u orchestrator-dashboard -f');
  await warnUnlessLinger(deps);
  return 0;
}

/**
 * Linger keeps user units alive past logout and starts them at boot. Off is
 * still exit 0 — the service IS running — but the warning is prominent, and
 * enabling is never auto-attempted (polkit can prompt/hang on headless boxes).
 */
async function warnUnlessLinger(deps: ServiceDeps): Promise<void> {
  let linger: string;
  try {
    const { stdout } = await deps.run('loginctl', ['show-user', deps.username, '--property=Linger']);
    linger = stdout.trim();
  } catch {
    deps.err(
      '⚠ could not determine linger status — without linger the service dies at ' +
        `logout and skips boots. Check: loginctl show-user ${deps.username} --property=Linger`,
    );
    return;
  }
  if (linger === 'Linger=yes') {
    deps.out('✔ linger is on — the service survives logout and starts at boot');
    return;
  }
  deps.err(
    [
      '',
      '⚠️  REQUIRED for reboot survival: lingering is OFF for this user, so the',
      '    service stops at logout and will not start at boot. Enable it with:',
      '',
      `      sudo loginctl enable-linger ${deps.username}`,
      '',
    ].join('\n'),
  );
}

export async function runServiceUninstall(deps: ServiceDeps): Promise<number> {
  try {
    await deps.run('systemctl', ['--user', 'disable', '--now', 'orchestrator', 'orchestrator-dashboard']);
    deps.out('✔ disabled and stopped orchestrator + orchestrator-dashboard');
  } catch {
    deps.err('⚠ could not disable orchestrator units (not installed?) — continuing');
  }
  for (const unitPath of [deps.unitPath, deps.dashboardUnitPath]) {
    const removed = deps.removeUnit(unitPath);
    deps.out(removed ? `✔ removed ${unitPath}` : `• ${unitPath} was not present`);
  }
  try {
    await deps.run('systemctl', ['--user', 'daemon-reload']);
  } catch {
    deps.err('⚠ daemon-reload failed — run `systemctl --user daemon-reload` yourself');
  }
  return 0;
}
