import { describe, expect, it, vi } from 'vitest';
import {
  buildUnitPathEnv,
  renderSystemdUnit,
  runServiceInstall,
  runServiceUninstall,
  type ServiceDeps,
} from './service.ts';

const UNIT_PATH = '/home/op/.config/systemd/user/orchestrator.service';

const values = {
  version: '1.2.3',
  date: '2026-07-10',
  nodePath: '/opt/node/bin/node',
  entryPath: '/opt/lib/node_modules/@nvergez/orchestrator/dist/index.js',
  pathEnv: '/opt/node/bin:/usr/bin',
};

describe('renderSystemdUnit', () => {
  const unit = renderSystemdUnit(values);

  it('stamps the generated-by header, pointing hand-edits at drop-ins', () => {
    expect(unit).toMatch(/^# Generated by orc service install \(1\.2\.3, 2026-07-10\)/);
    expect(unit).toContain('orchestrator.service.d/');
  });

  it('pins ExecStart to the absolute node + entry resolved at install time', () => {
    expect(unit).toContain(
      'ExecStart=/opt/node/bin/node /opt/lib/node_modules/@nvergez/orchestrator/dist/index.js',
    );
  });

  it('carries the decided [Service] directives (issue #74)', () => {
    expect(unit).toContain('Type=simple');
    expect(unit).toContain('EnvironmentFile=%h/.config/orchestrator/env');
    expect(unit).toContain('Environment=PATH=/opt/node/bin:/usr/bin');
    expect(unit).toContain('Environment=NODE_OPTIONS=--enable-source-maps');
    expect(unit).toContain('SyslogIdentifier=orchestrator');
    expect(unit).toContain('Restart=always');
    expect(unit).toContain('RestartSec=5');
    expect(unit).toContain('WantedBy=default.target');
  });

  it('omits After=/Wants= ordering and WorkingDirectory, per the spec', () => {
    expect(unit).not.toMatch(/^After=/m);
    expect(unit).not.toMatch(/^Wants=/m);
    expect(unit).not.toMatch(/^WorkingDirectory=/m);
  });
});

describe('buildUnitPathEnv', () => {
  it('orders bin dirs first, then the standard tail', () => {
    expect(buildUnitPathEnv(['/opt/node/bin', '/home/op/.local/bin'])).toBe(
      '/opt/node/bin:/home/op/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    );
  });

  it('dedupes repeats, keeping the first occurrence', () => {
    expect(buildUnitPathEnv(['/usr/bin', '/opt/node/bin', '/usr/bin'])).toBe(
      '/usr/bin:/opt/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin',
    );
  });
});

interface DepsOverrides {
  which?: (name: string) => string | null;
  run?: ServiceDeps['run'];
  resolveEntry?: () => string;
}

const makeDeps = (overrides: DepsOverrides = {}) => {
  const out: string[] = [];
  const err: string[] = [];
  const systemCalls: string[][] = [];
  const written: { path: string; content: string }[] = [];
  const deps: ServiceDeps = {
    out: (line) => out.push(line),
    err: (line) => err.push(line),
    run:
      overrides.run ??
      ((command, args) => {
        systemCalls.push([command, ...args]);
        if (command === 'loginctl') return Promise.resolve({ stdout: 'Linger=yes\n' });
        return Promise.resolve({ stdout: '' });
      }),
    execPath: '/opt/node/bin/node',
    which:
      overrides.which ??
      ((name) => (name === 'orca' ? '/home/op/.local/bin/orca' : `/opt/tools/bin/${name}`)),
    resolveEntry:
      overrides.resolveEntry ?? (() => '/opt/lib/node_modules/@nvergez/orchestrator/dist/index.js'),
    writeUnit: (path, content) => written.push({ path, content }),
    removeUnit: vi.fn(() => true),
    unitPath: UNIT_PATH,
    username: 'op',
    version: '1.2.3',
    today: '2026-07-10',
  };
  return { deps, out, err, systemCalls, written };
};

describe('runServiceInstall', () => {
  it('writes the unit, reloads, enables --now, and prints the path + journalctl hint', async () => {
    const { deps, out, systemCalls, written } = makeDeps();

    await expect(runServiceInstall(deps)).resolves.toBe(0);

    expect(written).toHaveLength(1);
    expect(written[0]?.path).toBe(UNIT_PATH);
    expect(written[0]?.content).toContain(
      'ExecStart=/opt/node/bin/node /opt/lib/node_modules/@nvergez/orchestrator/dist/index.js',
    );
    // dir(node) + dir(orca) + dir(claude), deduped, then the standard tail.
    expect(written[0]?.content).toContain(
      'Environment=PATH=/opt/node/bin:/home/op/.local/bin:/opt/tools/bin:' +
        '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    );
    expect(systemCalls).toContainEqual(['systemctl', '--user', 'daemon-reload']);
    expect(systemCalls).toContainEqual(['systemctl', '--user', 'enable', '--now', 'orchestrator']);
    expect(out.join('\n')).toContain(UNIT_PATH);
    expect(out.join('\n')).toContain('journalctl --user -u orchestrator -f');
  });

  it('fails fast when the systemd user manager is unreachable', async () => {
    const { deps, err, written } = makeDeps({
      run: (command, args) =>
        command === 'systemctl' && args.includes('show-environment')
          ? Promise.reject(new Error('Failed to connect to bus'))
          : Promise.resolve({ stdout: '' }),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('run `orc` under your own supervisor');
    expect(written).toHaveLength(0);
  });

  it('fails when orca is not on PATH — the unit would be born broken', async () => {
    const { deps, err, written } = makeDeps({ which: () => null });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('`orca` not found on PATH');
    expect(written).toHaveLength(0);
  });

  it('only warns when claude is missing, and leaves its dir off the unit PATH', async () => {
    const { deps, err, written } = makeDeps({
      which: (name) => (name === 'orca' ? '/home/op/.local/bin/orca' : null),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(0);
    expect(err.join('\n')).toContain('`claude` not found on PATH');
    expect(written[0]?.content).toContain(
      'Environment=PATH=/opt/node/bin:/home/op/.local/bin:' +
        '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    );
  });

  it('fails with a build hint when dist/index.js is missing', async () => {
    const { deps, err, written } = makeDeps({
      resolveEntry: () => {
        throw Object.assign(new Error('ENOENT'), { code: 'ENOENT' });
      },
    });

    await expect(runServiceInstall(deps)).resolves.toBe(1);
    expect(err.join('\n')).toContain('npm run build');
    expect(written).toHaveLength(0);
  });

  it('still exits 0 with linger off, but prints the exact sudo one-liner', async () => {
    const { deps, err } = makeDeps({
      run: (command) =>
        command === 'loginctl'
          ? Promise.resolve({ stdout: 'Linger=no\n' })
          : Promise.resolve({ stdout: '' }),
    });

    await expect(runServiceInstall(deps)).resolves.toBe(0);
    expect(err.join('\n')).toContain('REQUIRED for reboot survival');
    expect(err.join('\n')).toContain('sudo loginctl enable-linger op');
  });

  it('never runs enable-linger itself — the warning is the whole reaction', async () => {
    const { deps, systemCalls } = makeDeps({
      run: (command, args) => {
        systemCalls.push([command, ...args]);
        return command === 'loginctl'
          ? Promise.resolve({ stdout: 'Linger=no\n' })
          : Promise.resolve({ stdout: '' });
      },
    });

    await runServiceInstall(deps);
    expect(systemCalls.some((call) => call.includes('enable-linger'))).toBe(false);
  });
});

describe('runServiceUninstall', () => {
  it('disables --now, removes the unit, and reloads', async () => {
    const { deps, systemCalls } = makeDeps();

    await expect(runServiceUninstall(deps)).resolves.toBe(0);

    expect(systemCalls).toContainEqual(['systemctl', '--user', 'disable', '--now', 'orchestrator']);
    expect(deps.removeUnit).toHaveBeenCalledWith(UNIT_PATH);
    expect(systemCalls).toContainEqual(['systemctl', '--user', 'daemon-reload']);
  });

  it('keeps going when the unit was never installed', async () => {
    const { deps } = makeDeps({
      run: (command, args) =>
        args.includes('disable')
          ? Promise.reject(new Error('Unit orchestrator.service not loaded.'))
          : Promise.resolve({ stdout: '' }),
    });
    vi.mocked(deps.removeUnit).mockReturnValue(false);

    await expect(runServiceUninstall(deps)).resolves.toBe(0);
  });
});
